[project]
name = "house-price-pred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.100.0",
    "requests>=2.28.0",
    "uvicorn>=0.20.0",
    "matplotlib",
]

[tool.uv]
package = false

[project.scripts]
house-price-pred = "house_price_pred:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
